# Generated by Django 4.2.6 on 2023-11-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
