# Generated by Django 5.0 on 2023-12-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloc', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
