# Generated by Django 5.0 on 2023-12-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweatshirts', '0004_alter_sweatshirts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweatshirts',
            name='act',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sweatshirts',
            name='cost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sweatshirts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sweatshirts',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sweatshirts',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
