# Generated by Django 5.0 on 2023-12-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweatshirts', '0005_alter_sweatshirts_act_alter_sweatshirts_cost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SweatShirts',
        ),
    ]
