# Generated by Django 4.2.6 on 2023-11-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='things',
            old_name='ACT',
            new_name='act',
        ),
    ]
